---
- name: Automatic Remediation of a webserver
  hosts: all
  sources:
    - name: listen for alerts
      benthomasson.eda.alertmanager:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: debug
      condition: event.alert.labels.job == "fastapi"
      action:
        debug:
